package com.tilab.spine.packets;

/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'DataPkt'
 * message type.
 */

public class DataPkt extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 12;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 13;

    /** Create a new DataPkt of size 12. */
    public DataPkt() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new DataPkt of the given data_length. */
    public DataPkt(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataPkt with the given data_length
     * and base offset.
     */
    public DataPkt(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataPkt using the given byte array
     * as backing store.
     */
    public DataPkt(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataPkt using the given byte array
     * as backing store, with the given base offset.
     */
    public DataPkt(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataPkt using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public DataPkt(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataPkt embedded in the given message
     * at the given base offset.
     */
    public DataPkt(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataPkt embedded in the given message
     * at the given base offset and length.
     */
    public DataPkt(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <DataPkt> \n";
      try {
        s += "  [part=";
        for (int i = 0; i < 6; i++) {
          s += "0x"+Long.toHexString(getElement_part(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [feature=";
        for (int i = 0; i < 3; i++) {
          s += "0x"+Long.toHexString(getElement_feature(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: part
    //   Field type: short[], signed
    //   Offset (bits): 0
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'part' is signed (true).
     */
    public static boolean isSigned_part() {
        return true;
    }

    /**
     * Return whether the field 'part' is an array (true).
     */
    public static boolean isArray_part() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'part'
     */
    public static int offset_part(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 6) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'part'
     */
    public static int offsetBits_part(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 6) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'part' as a short[]
     */
    public short[] get_part() {
        short[] tmp = new short[6];
        for (int index0 = 0; index0 < numElements_part(0); index0++) {
            tmp[index0] = getElement_part(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'part' from the given short[]
     */
    public void set_part(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_part(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'part'
     */
    public short getElement_part(int index1) {
        return (short)getUIntBEElement(offsetBits_part(index1), 8);
    }

    /**
     * Set an element of the array 'part'
     */
    public void setElement_part(int index1, short value) {
        setUIntBEElement(offsetBits_part(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'part'
     */
    public static int totalSize_part() {
        return (48 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'part'
     */
    public static int totalSizeBits_part() {
        return 48;
    }

    /**
     * Return the size, in bytes, of each element of the array 'part'
     */
    public static int elementSize_part() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'part'
     */
    public static int elementSizeBits_part() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'part'
     */
    public static int numDimensions_part() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'part'
     */
    public static int numElements_part() {
        return 6;
    }

    /**
     * Return the number of elements in the array 'part'
     * for the given dimension.
     */
    public static int numElements_part(int dimension) {
      int array_dims[] = { 6,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'part' with a String
     */
    public void setString_part(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_part(i, (short)s.charAt(i));
         }
         setElement_part(i, (short)0); //null terminate
    }

    /**
     * Read the array 'part' as a String
     */
    public String getString_part() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,6)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_part(i) == (char)0) break;
             carr[i] = (char)getElement_part(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: feature
    //   Field type: short[], signed
    //   Offset (bits): 48
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'feature' is signed (true).
     */
    public static boolean isSigned_feature() {
        return true;
    }

    /**
     * Return whether the field 'feature' is an array (true).
     */
    public static boolean isArray_feature() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'feature'
     */
    public static int offset_feature(int index1) {
        int offset = 48;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'feature'
     */
    public static int offsetBits_feature(int index1) {
        int offset = 48;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'feature' as a short[]
     */
    public short[] get_feature() {
        short[] tmp = new short[3];
        for (int index0 = 0; index0 < numElements_feature(0); index0++) {
            tmp[index0] = getElement_feature(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'feature' from the given short[]
     */
    public void set_feature(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_feature(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'feature'
     */
    public short getElement_feature(int index1) {
        return (short)getSIntBEElement(offsetBits_feature(index1), 16);
    }

    /**
     * Set an element of the array 'feature'
     */
    public void setElement_feature(int index1, short value) {
        setSIntBEElement(offsetBits_feature(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'feature'
     */
    public static int totalSize_feature() {
        return (48 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'feature'
     */
    public static int totalSizeBits_feature() {
        return 48;
    }

    /**
     * Return the size, in bytes, of each element of the array 'feature'
     */
    public static int elementSize_feature() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'feature'
     */
    public static int elementSizeBits_feature() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'feature'
     */
    public static int numDimensions_feature() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'feature'
     */
    public static int numElements_feature() {
        return 3;
    }

    /**
     * Return the number of elements in the array 'feature'
     * for the given dimension.
     */
    public static int numElements_feature(int dimension) {
      int array_dims[] = { 3,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
