COMPONENT=BaseStationC
#CFLAGS += -DCC2420_NO_ACKNOWLEDGEMENTS
#CFLAGS += -DCC2420_NO_ADDRESS_RECOGNITION
PFLAGS += -DCC2420_DEF_CHANNEL=14

PFLAGS += -I..
include ../../../Makefile.spine
include ../../../Makefile.upma
include $(MAKERULES)

